- name: Configuring control machine
  hosts: cm


  tasks:
  - stat: path=/etc/yum.repos.d/kubernetes.repo
    register: kuberepo
    become: yes

  - name: Create Kubernetes repo file if not exist.
    file: 
      path=/etc/yum.repos.d/kubernetes.repo
      owner=root
      group=root
      mode=0644
      state={{ "file" if  kuberepo.stat.exists else "touch"}}
    become: yes

  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
      path: /etc/yum.repos.d/kubernetes.repo
      block: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    become: yes

  - name: Ensure a list of packages installed
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - kubectl
      - bash-completion
    become: yes

  - name: create .kube directory for student user
    file:
      path: /home/student/.kube
      state: directory
      mode: 0755

  - name: copy k8s conf to student dir
    copy:
      src: admin-config
      dest: /home/student/.kube/config
      owner: student
      group: student

  - name: Add node worker label worker
    shell: |
      kubectl patch node worker --patch='{"metadata":{"labels":{"node-role.kubernetes.io/worker":""}}}' 