- name: Initial Docker deploy for Vagrant VM
  hosts: k8s-cluster
  become: yes

  tasks:
  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo

  - name: Enable Docker Edge repo
    ini_file:
      dest: /etc/yum.repos.d/docer-ce.repo
      section: 'docker-ce-edge'
      option: enabled
      value: 0

  - name: Ensure a list of packages installed
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - deltarpm
      - epel-release
      - wget 
      - ntp 
      - jq 
      - net-tools
      - bind-utils 
      - moreutils
      - docker-ce

  - name: Add user vagrant to docker group
    user:
      name: vagrant
      groups: docker
      append: yes
  
  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: Start Ntpd service
    service:
      name: ntpd
      state: started
      enabled: yes

  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Remove swapfile from /etc/fstab
    mount:
      name: swap
      fstype: swap
      state: absent

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - stat: path=/etc/yum.repos.d/kubernetes.repo
    register: kuberepo

  - name: Create Kubernetes repo file if not exist.
    file: 
      path=/etc/yum.repos.d/kubernetes.repo
      owner=root
      group=root
      mode=0644
      state={{ "file" if  kuberepo.stat.exists else "touch"}}

  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
      path: /etc/yum.repos.d/kubernetes.repo
      block: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  
  - name: Copy a Docker daemon.json
    copy:
      src: daemon.json
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: '0644'
    register: daemonconfig
    
  - name: Ensure a list of kubernetes packages installed
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni

  - name: Add fix for Vagrant
    replace:
      path: /etc/sysconfig/kubelet
      regexp: '=.*'
      replace: '=--node-ip={{ ansible_eth1.ipv4.address }}'

  - name: Restart Docker service
    service:
      name: docker
      state: restarted
    when: daemonconfig.changed

  - name: Enable Kubelet service
    service:
      name: kubelet
      enabled: yes

  - name: Adding setting to enable passing bridged IPv4 traffic to iptables' chain
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      sysctl_file: /etc/sysctl.d/docker.conf
      reload: no

  - name: Adding setting to enable passing bridged IPv6 traffic to iptables' chain
    sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      sysctl_file: /etc/sysctl.d/docker.conf
      reload: yes  