---
- name: Checking if metallb already exist
  shell: kubectl get deploy controller -n metallb-system
  ignore_errors: yes
  register: metallb_deploy
  changed_when: no

- name: Deploying  metallb components
  shell: kubectl apply -f {{metallb_url}}
  when: metallb_deploy.stdout == ""
  register: metallb
  notify: save metallb fact

- name: Checking if metallb config already exist
  shell: kubectl get configmaps config -n metallb-system
  ignore_errors: yes
  register: metallb_config
  changed_when: no

- stat: path=/tmp/metallb-config.yml
  register: configfile

- name: Create Config file if not exist.
  file: 
    path=/tmp/metallb-config.yml
    state={{ "file" if  configfile.stat.exists else "touch"}}

- name: Generate config file
  blockinfile:
    path: /tmp/metallb-config.yml
    block: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: metallb-system
        name: config
      data:
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - {{metallb_network_cidr}}
  when: metallb_config.stdout == ""
  register: config_file

- name: Deploy metallb config
  shell: kubectl apply -f /tmp/metallb-config.yml
  when: config_file.changed


  
      
  