---
- name: Check if fact dir exist
  file: 
    path: /etc/ansible/facts.d
    state: directory
  become: yes
  listen: save metallb fact
  
- name: Get metallb image
  shell: "kubectl get deploy controller -n metallb-system -o jsonpath={.spec.template.spec.containers[0].image}"
  register: metallb_image
  changed_when: no
  listen: save metallb fact

- name: Create metallb fact
  copy:
    content: |
      {
        "image": "{{metallb_image.stdout}}",
        "cidr": "{{metallb_network_cidr}}"
      }
    dest: /etc/ansible/facts.d/kubernetes_metallb.fact
  become: yes
  listen: save metallb fact